name: ShootingScoreboard
version: '${project.version}'
main: com.slm.ShootingScoreboard
api-version: '1.20'
load: STARTUP
authors: [Xiaoslm_666]
description: ShootingScoreboard
website: xiao-slm.github.io


commands:
  scorerun:
    usage: /scorerun
    description: 启动或关闭scoreboard
  scorereload:
    usage: /scorereload
    description: 重载scoreboard配置
  